apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: xrvcjqvxp-python 
  janus-idp.io/tekton: xrvcjqvxp-python
  backstage.io/kubernetes-id: xrvcjqvxp-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: xrvcjqvxp-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml