apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xrvcjqvxp-python
  janus-idp.io/tekton: xrvcjqvxp-python
  backstage.io/kubernetes-id: xrvcjqvxp-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: xrvcjqvxp-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
